spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doa?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: root
  application:
    name: DOA

server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/

